name: example
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sizing:

dev_dependencies:
  flutter_test:
    sdk: flutter
  # test: ^1.15.7

dependency_overrides:
  sizing:
    path: ../

